# Generated by Django 4.2.7 on 2023-11-17 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Terapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'terapia',
                'verbose_name_plural': 'terapias',
            },
        ),
        migrations.CreateModel(
            name='Terapeutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted', models.TextField()),
                ('register', models.TimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last_name')),
                ('description', models.TextField(verbose_name='description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terapeutas', to=settings.AUTH_USER_MODEL)),
                ('terapias', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='terapeutas.terapia')),
            ],
            options={
                'verbose_name': 'terapeuta',
                'verbose_name_plural': 'terapeutas',
                'ordering': ['id'],
            },
        ),
    ]
